In [1]:
import numpy as np

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(arr.size)

10


In [5]:
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
arr = [1,2,0,0,4,0]

In [15]:
print(arr.index)

<built-in method index of list object at 0x7f8fb9da2a00>


In [16]:
arr.index

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [18]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [21]:
print(type(nz))

<class 'tuple'>


In [22]:
id_mat = np.identity(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
ran_mat = np.random.random((3,3,3))
print(ran_mat)

[[[0.3261385  0.87008175 0.69379073]
  [0.32611553 0.07670554 0.92796308]
  [0.53299581 0.15583598 0.7951478 ]]

 [[0.07951546 0.51828906 0.3501674 ]
  [0.31908677 0.8024096  0.13278883]
  [0.35983359 0.20463415 0.11261601]]

 [[0.6598634  0.90260077 0.80035286]
  [0.93542281 0.11592136 0.56749293]
  [0.36826184 0.35396817 0.09256844]]]


In [30]:
ran_mat = np.random.random((10,10))
#print(ran_mat)
Zmin, Zmax = ran_mat.min(), ran_mat.max()
print(Zmin, Zmax)

0.0041529225748810905 0.9910190487768199
